
server:
  port: 8080
  servlet:
    context-path: /
      #session:
    #timeout: 0

spring:
  datasource:
    url: jdbc:sqlite:C:/Users/dell/Downloads/SRSystem.db
    username:
    password:
    driver-class-name:
  jackson:
    time-zone: GMT-5